language: cpp
os: linux
branches:
  only:
    - master
    - travis

env:
  global:
    - GIT_USER="dasfranck"
    - GIT_DISPLAY_NAME="TRAVIS (dasfranck)"
    - GIT_EMAIL="dasfranck@gmx.com"
    - REPO_UNITY="github.com/RoukaVici/Asset-Unity"
    - REPO_UNREAL="github.com/RoukaVici/Asset-Unreal-Engine"
    - BRANCH="travis"
    - GCC="CC=gcc-8 && CXX=g++-8"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      - gcc-8
      - g++-8
      - gcc-mingw-w64-base
      - binutils-mingw-w64-x86-64
      - gcc-mingw-w64-x86-64
      - gcc-mingw-w64
      - g++-mingw-w64-x86-64
      - git
      - libbluetooth-dev

before_install:
  - eval "${GCC}"
script:
  - mkdir build-linux64
  - cd build-linux64
  - cmake -DTESTS=TRUE ..
  - cmake --build .
  - cd ..

  - mkdir build-windows
  - cd build-windows
  - cmake -DCMAKE_TOOLCHAIN_FILE=../toolchain/mingw64.cmake ..
  - cmake --build .
  - cd ..
after_success:
  - cd ..
  - git config --global user.email "$GIT_EMAIL"
  - git config --global user.name "$GIT_DISPLAY_NAME"

  # Unity
  - git clone git://$REPO_UNITY
  - cd Asset-Unity
  - git checkout -b $BRANCH
  - git pull origin $BRANCH
  - cp ../LibRoukaVici/output/libroukavici.so Assets/Plugins/x64/libroukavici.so
  - cp ../LibRoukaVici/output/libroukavici.dll Assets/Plugins/x64/roukavici.dll
  - git add Assets/Plugins/x64/libroukavici.so
  - git add Assets/Plugins/x64/roukavici.dll
  - git commit -m "TRAVIS Pushing LibRoukaVici version $TRAVIS_COMMIT"
  - git push https://$GIT_USER:$GITHUB_API_KEY@$REPO_UNITY $BRANCH &2>/dev/null
  - cd ..

  # UNREAL
  - git clone git://$REPO_UNREAL
  - cd Asset-Unreal-Engine
  - git checkout -b $BRANCH
  - git pull origin/travis
  # COPY HERE FILES FROM BUILD
  # ADD FILES IN COMMIT
  - git commit -m 'TRAVIS Pushing LibRoukaVici version $TRAVIS_COMMIT'
  - git push https://$GIT_USER:$GITHUB_API_KEY@$REPO_UNREAL $BRANCH &2>/dev/null