language: cpp
os: linux
branches:
  only:
    - master
    - travis

env:
  global:
    - GIT_USER="dasfranck"
    - GIT_DISPLAY_NAME="TRAVIS (dasfranck)"
    - GIT_EMAIL="dasfranck@gmx.com"
    - REPO_UNITY="github.com/RoukaVici/Asset-Unity"
    - REPO_UNREAL="github.com/RoukaVici/Asset-Unreal-Engine"
    - BRANCH="travis"
    - GCC="CC=gcc-8 && CXX=g++-8"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      - gcc-8
      - g++-8
      - git
      - libbluetooth-dev

before_install:
  - eval "${GCC}"
script:
  - mkdir build
  - cd build
  - cmake -DTESTS=TRUE ..
  - cmake --build .
  - cd ..
after_success:
  - MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
  - git config --global user.email "$GIT_EMAIL"
  - git config --global user.email "$GIT_DISPLAY_NAME"
  - cd ..
  - git clone --depth=1 git://$REPO_UNREAL
  - git clone --depth=1 git://$REPO_UNITY

  # Unity
  - cd Asset-Unity
  - git checkout -b $BRANCH
  - cp ../LibRoukaVici/output/libroukavici.so Assets/Plugins/x64/libroukavici.so
  - git add Assets/Plugins/x64/libroukavici.so
  - git commit -m 'TRAVIS Pushing LibRoukaVici version $TRAVIS_COMMIT'
  - git push -f -q https://$GIT_USER:$GITHUB_API_KEY@$REPO_UNITY dev &2>/dev/null

  # UNREAL
  - cd ../Asset-Unreal
  - git checkout -b $BRANCH
  # COPY HERE FILES FROM BUILD
  # ADD FILES IN COMMIT
  - git commit -m 'TRAVIS Pushing LibRoukaVici version $TRAVIS_COMMIT'
  - git push -f -q https://$GIT_USER:$GITHUB_API_KEY@$REPO_UNREAL dev &2>/dev/null