# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/navenn_t/Programming/cpp/RoukaVici-lib

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/navenn_t/Programming/cpp/RoukaVici-lib

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/navenn_t/Programming/cpp/RoukaVici-lib/CMakeFiles /home/navenn_t/Programming/cpp/RoukaVici-lib/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/navenn_t/Programming/cpp/RoukaVici-lib/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named roukavici

# Build rule for target.
roukavici: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 roukavici
.PHONY : roukavici

# fast build rule for target.
roukavici/fast:
	$(MAKE) -f CMakeFiles/roukavici.dir/build.make CMakeFiles/roukavici.dir/build
.PHONY : roukavici/fast

#=============================================================================
# Target rules for targets named roukavici_test

# Build rule for target.
roukavici_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 roukavici_test
.PHONY : roukavici_test

# fast build rule for target.
roukavici_test/fast:
	$(MAKE) -f CMakeFiles/roukavici_test.dir/build.make CMakeFiles/roukavici_test.dir/build
.PHONY : roukavici_test/fast

src/RoukaVici.o: src/RoukaVici.cpp.o

.PHONY : src/RoukaVici.o

# target to build an object file
src/RoukaVici.cpp.o:
	$(MAKE) -f CMakeFiles/roukavici.dir/build.make CMakeFiles/roukavici.dir/src/RoukaVici.cpp.o
.PHONY : src/RoukaVici.cpp.o

src/RoukaVici.i: src/RoukaVici.cpp.i

.PHONY : src/RoukaVici.i

# target to preprocess a source file
src/RoukaVici.cpp.i:
	$(MAKE) -f CMakeFiles/roukavici.dir/build.make CMakeFiles/roukavici.dir/src/RoukaVici.cpp.i
.PHONY : src/RoukaVici.cpp.i

src/RoukaVici.s: src/RoukaVici.cpp.s

.PHONY : src/RoukaVici.s

# target to generate assembly for a file
src/RoukaVici.cpp.s:
	$(MAKE) -f CMakeFiles/roukavici.dir/build.make CMakeFiles/roukavici.dir/src/RoukaVici.cpp.s
.PHONY : src/RoukaVici.cpp.s

src/TCPManager.o: src/TCPManager.cpp.o

.PHONY : src/TCPManager.o

# target to build an object file
src/TCPManager.cpp.o:
	$(MAKE) -f CMakeFiles/roukavici.dir/build.make CMakeFiles/roukavici.dir/src/TCPManager.cpp.o
.PHONY : src/TCPManager.cpp.o

src/TCPManager.i: src/TCPManager.cpp.i

.PHONY : src/TCPManager.i

# target to preprocess a source file
src/TCPManager.cpp.i:
	$(MAKE) -f CMakeFiles/roukavici.dir/build.make CMakeFiles/roukavici.dir/src/TCPManager.cpp.i
.PHONY : src/TCPManager.cpp.i

src/TCPManager.s: src/TCPManager.cpp.s

.PHONY : src/TCPManager.s

# target to generate assembly for a file
src/TCPManager.cpp.s:
	$(MAKE) -f CMakeFiles/roukavici.dir/build.make CMakeFiles/roukavici.dir/src/TCPManager.cpp.s
.PHONY : src/TCPManager.cpp.s

src/TextManager.o: src/TextManager.cpp.o

.PHONY : src/TextManager.o

# target to build an object file
src/TextManager.cpp.o:
	$(MAKE) -f CMakeFiles/roukavici.dir/build.make CMakeFiles/roukavici.dir/src/TextManager.cpp.o
.PHONY : src/TextManager.cpp.o

src/TextManager.i: src/TextManager.cpp.i

.PHONY : src/TextManager.i

# target to preprocess a source file
src/TextManager.cpp.i:
	$(MAKE) -f CMakeFiles/roukavici.dir/build.make CMakeFiles/roukavici.dir/src/TextManager.cpp.i
.PHONY : src/TextManager.cpp.i

src/TextManager.s: src/TextManager.cpp.s

.PHONY : src/TextManager.s

# target to generate assembly for a file
src/TextManager.cpp.s:
	$(MAKE) -f CMakeFiles/roukavici.dir/build.make CMakeFiles/roukavici.dir/src/TextManager.cpp.s
.PHONY : src/TextManager.cpp.s

src/USBManager.o: src/USBManager.cpp.o

.PHONY : src/USBManager.o

# target to build an object file
src/USBManager.cpp.o:
	$(MAKE) -f CMakeFiles/roukavici.dir/build.make CMakeFiles/roukavici.dir/src/USBManager.cpp.o
.PHONY : src/USBManager.cpp.o

src/USBManager.i: src/USBManager.cpp.i

.PHONY : src/USBManager.i

# target to preprocess a source file
src/USBManager.cpp.i:
	$(MAKE) -f CMakeFiles/roukavici.dir/build.make CMakeFiles/roukavici.dir/src/USBManager.cpp.i
.PHONY : src/USBManager.cpp.i

src/USBManager.s: src/USBManager.cpp.s

.PHONY : src/USBManager.s

# target to generate assembly for a file
src/USBManager.cpp.s:
	$(MAKE) -f CMakeFiles/roukavici.dir/build.make CMakeFiles/roukavici.dir/src/USBManager.cpp.s
.PHONY : src/USBManager.cpp.s

src/VibrationGroup.o: src/VibrationGroup.cpp.o

.PHONY : src/VibrationGroup.o

# target to build an object file
src/VibrationGroup.cpp.o:
	$(MAKE) -f CMakeFiles/roukavici.dir/build.make CMakeFiles/roukavici.dir/src/VibrationGroup.cpp.o
.PHONY : src/VibrationGroup.cpp.o

src/VibrationGroup.i: src/VibrationGroup.cpp.i

.PHONY : src/VibrationGroup.i

# target to preprocess a source file
src/VibrationGroup.cpp.i:
	$(MAKE) -f CMakeFiles/roukavici.dir/build.make CMakeFiles/roukavici.dir/src/VibrationGroup.cpp.i
.PHONY : src/VibrationGroup.cpp.i

src/VibrationGroup.s: src/VibrationGroup.cpp.s

.PHONY : src/VibrationGroup.s

# target to generate assembly for a file
src/VibrationGroup.cpp.s:
	$(MAKE) -f CMakeFiles/roukavici.dir/build.make CMakeFiles/roukavici.dir/src/VibrationGroup.cpp.s
.PHONY : src/VibrationGroup.cpp.s

src/exported/RoukaViciAPI.o: src/exported/RoukaViciAPI.cpp.o

.PHONY : src/exported/RoukaViciAPI.o

# target to build an object file
src/exported/RoukaViciAPI.cpp.o:
	$(MAKE) -f CMakeFiles/roukavici.dir/build.make CMakeFiles/roukavici.dir/src/exported/RoukaViciAPI.cpp.o
.PHONY : src/exported/RoukaViciAPI.cpp.o

src/exported/RoukaViciAPI.i: src/exported/RoukaViciAPI.cpp.i

.PHONY : src/exported/RoukaViciAPI.i

# target to preprocess a source file
src/exported/RoukaViciAPI.cpp.i:
	$(MAKE) -f CMakeFiles/roukavici.dir/build.make CMakeFiles/roukavici.dir/src/exported/RoukaViciAPI.cpp.i
.PHONY : src/exported/RoukaViciAPI.cpp.i

src/exported/RoukaViciAPI.s: src/exported/RoukaViciAPI.cpp.s

.PHONY : src/exported/RoukaViciAPI.s

# target to generate assembly for a file
src/exported/RoukaViciAPI.cpp.s:
	$(MAKE) -f CMakeFiles/roukavici.dir/build.make CMakeFiles/roukavici.dir/src/exported/RoukaViciAPI.cpp.s
.PHONY : src/exported/RoukaViciAPI.cpp.s

test/main.o: test/main.cpp.o

.PHONY : test/main.o

# target to build an object file
test/main.cpp.o:
	$(MAKE) -f CMakeFiles/roukavici_test.dir/build.make CMakeFiles/roukavici_test.dir/test/main.cpp.o
.PHONY : test/main.cpp.o

test/main.i: test/main.cpp.i

.PHONY : test/main.i

# target to preprocess a source file
test/main.cpp.i:
	$(MAKE) -f CMakeFiles/roukavici_test.dir/build.make CMakeFiles/roukavici_test.dir/test/main.cpp.i
.PHONY : test/main.cpp.i

test/main.s: test/main.cpp.s

.PHONY : test/main.s

# target to generate assembly for a file
test/main.cpp.s:
	$(MAKE) -f CMakeFiles/roukavici_test.dir/build.make CMakeFiles/roukavici_test.dir/test/main.cpp.s
.PHONY : test/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... roukavici"
	@echo "... roukavici_test"
	@echo "... src/RoukaVici.o"
	@echo "... src/RoukaVici.i"
	@echo "... src/RoukaVici.s"
	@echo "... src/TCPManager.o"
	@echo "... src/TCPManager.i"
	@echo "... src/TCPManager.s"
	@echo "... src/TextManager.o"
	@echo "... src/TextManager.i"
	@echo "... src/TextManager.s"
	@echo "... src/USBManager.o"
	@echo "... src/USBManager.i"
	@echo "... src/USBManager.s"
	@echo "... src/VibrationGroup.o"
	@echo "... src/VibrationGroup.i"
	@echo "... src/VibrationGroup.s"
	@echo "... src/exported/RoukaViciAPI.o"
	@echo "... src/exported/RoukaViciAPI.i"
	@echo "... src/exported/RoukaViciAPI.s"
	@echo "... test/main.o"
	@echo "... test/main.i"
	@echo "... test/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

